export const DEVICE_TYPE_COLORS = {
  camera:        '#5E5CE6',
  computer:      '#26C281',
  phone:         '#F2C94C',
  iot:           '#F07D38',
  router:        '#06B6D4',
  tablet:        '#D946EF',
  tv:            '#7C3AED',
  printer:       '#14B8A6',
  smart_speaker: '#A3E635',
  game_console:  '#EF4444',
  nas:           '#60A5FA',
  wearable:      '#FB7185',
  unknown:       '#8B8B96',
}

export const DEVICE_TYPE_LABELS = {
  camera:        '摄像头',
  computer:      '电脑',
  phone:         '手机',
  iot:           'IoT',
  router:        '路由器',
  tablet:        '平板',
  tv:            '电视',
  printer:       '打印机',
  smart_speaker: '智能音箱',
  game_console:  '游戏机',
  nas:           'NAS',
  wearable:      '可穿戴',
  unknown:       '未知',
}
